"""Adding geo Column to PropertyBase

Revision ID: 4d5296ae69df
Revises: 9dd103b657c0
Create Date: 2020-10-13 10:33:58.803504

"""
from alembic import op
from geoalchemy2 import Geometry
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5296ae69df'
down_revision = '9dd103b657c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_bases', sa.Column('geo', Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_bases', 'geo')
    # ### end Alembic commands ###
