"""empty message

Revision ID: 67d1f60ef4f9
Revises: 4a77e4f2c0ca
Create Date: 2020-05-04 13:50:51.005324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d1f60ef4f9'
down_revision = '4a77e4f2c0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_desc', sa.String(), nullable=True),
    sa.Column('deactivated_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_bases')
    # ### end Alembic commands ###
