"""server_default

Revision ID: 717c385ef587
Revises: 39b723c41043
Create Date: 2020-10-02 12:10:31.732766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717c385ef587'
down_revision = '39b723c41043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_bases', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_bases', 'enabled')
    # ### end Alembic commands ###
