"""added enabled and uuid to property assets

Revision ID: 9dd103b657c0
Revises: 717c385ef587
Create Date: 2020-10-11 14:51:32.130296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd103b657c0'
down_revision = '717c385ef587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_assets', sa.Column('deactivated_date', sa.DateTime(), nullable=True))
    op.add_column('property_assets', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('property_assets', sa.Column('uuid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'property_assets', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_assets', type_='unique')
    op.drop_column('property_assets', 'uuid')
    op.drop_column('property_assets', 'enabled')
    op.drop_column('property_assets', 'deactivated_date')
    # ### end Alembic commands ###
