"""empty message

Revision ID: f866129b49a6
Revises: 67d1f60ef4f9
Create Date: 2020-05-06 12:27:58.067030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f866129b49a6'
down_revision = '67d1f60ef4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_bases', sa.Column('asking_price', sa.Integer(), nullable=True))
    op.add_column('property_bases', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('property_bases', sa.Column('legal_description', sa.String(), nullable=True))
    op.add_column('property_bases', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('property_bases', sa.Column('lot_size', sa.String(), nullable=True))
    op.add_column('property_bases', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('property_bases', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('property_bases', sa.Column('year_built', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'property_bases', ['uuid'])
    op.drop_column('property_bases', 'property_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_bases', sa.Column('property_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'property_bases', type_='unique')
    op.drop_column('property_bases', 'year_built')
    op.drop_column('property_bases', 'uuid')
    op.drop_column('property_bases', 'postal_code')
    op.drop_column('property_bases', 'lot_size')
    op.drop_column('property_bases', 'longitude')
    op.drop_column('property_bases', 'legal_description')
    op.drop_column('property_bases', 'latitude')
    op.drop_column('property_bases', 'asking_price')
    # ### end Alembic commands ###
